// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var LodashGet = require("lodash.get");
var Belt_Result = require("bs-platform/lib/js/belt_Result.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function mount(flags, elementId, $staropt$star, elmProgram) {
  var moduleName = $staropt$star !== undefined ? $staropt$star : "Main";
  var maybeModule = LodashGet(elmProgram, "Elm." + moduleName);
  if (maybeModule == null) {
    return /* Error */Block.__(1, ["Module '" + (moduleName + "' not found.")]);
  } else {
    var maybeFlags = flags;
    var maybeElementId = elementId;
    var module_ = maybeModule;
    var resultOptions;
    if (maybeElementId !== undefined) {
      var elementId$1 = maybeElementId;
      if (maybeFlags !== undefined) {
        var match = document.getElementById(elementId$1);
        resultOptions = (match == null) ? /* Error */Block.__(1, ["Element with id '" + (elementId$1 + "' wasn't found.")]) : /* Ok */Block.__(0, [{
                node: match,
                flags: Caml_option.valFromOption(maybeFlags)
              }]);
      } else {
        var match$1 = document.getElementById(elementId$1);
        resultOptions = (match$1 == null) ? /* Error */Block.__(1, ["Element with id '" + (elementId$1 + "' wasn't found.")]) : /* Ok */Block.__(0, [{
                node: match$1
              }]);
      }
    } else {
      resultOptions = maybeFlags !== undefined ? /* Ok */Block.__(0, [{
              flags: Caml_option.valFromOption(maybeFlags)
            }]) : /* Ok */Block.__(0, [{ }]);
    }
    return Belt_Result.map(resultOptions, (function (options) {
                  return module_.init(options);
                }));
  }
}

var R = 0;

exports.R = R;
exports.mount = mount;
/* lodash.get Not a pure module */
